export const knowledgeBase = {
  engine: {
    category: 'engine',
    title: 'Engine / Starting Issues',
    keywords: [
      'engine',
      'won t start',
      'not starting',
      'stuck',
      'cranks',
      'stall',
      'misfire',
      'rough idle',
      'engine light',
      'not starting',
      'does not start',
      'doesn’t start',
      'clicking',
      'crank',
    ],
    symptoms: [
      'Vehicle will not start, cranks but does not fire, or starts intermittently',
      'Engine stalls, runs rough, or misfires',
      'Delayed or unusual starting behavior',
    ],
    questions: [
      'When you try to start the vehicle, does it crank normally or do nothing at all?',
      'Is the issue constant or intermittent?',
      'Do the dashboard lights appear to be working?',
      'When did the issue start, and has the battery recently been replaced?',
    ],
    guidance: [
      'Check whether the battery is healthy and whether the vehicle is receiving power.',
      'If the engine is not starting and there are signs of smoke, burning, or fuel smell, stop and seek professional help immediately.',
      'Do not attempt complex engine repairs without the correct tools and training.',
    ],
    safetyLevel: 'caution',
  },
  battery: {
    category: 'battery',
    title: 'Battery / Electrical Issues',
    keywords: [
      'battery',
      'dead battery',
      'electrical',
      'lights',
      'dashboard',
      'clicking',
      'window',
      'radio',
      'power',
    ],
    symptoms: [
      'Vehicle is slow to start or will not turn over',
      'Warning lights flicker, electronics are weak, or the battery is drained',
      'Electrical faults such as windows, locks, lights, or radio not working correctly',
    ],
    questions: [
      'Do you hear a click when trying to start the vehicle?',
      'Have the lights or other electrical systems been weak or dim?',
      'How old is the battery, and has it recently been replaced or tested?',
      'Does the problem happen mainly after the vehicle has been parked for a long period?',
    ],
    guidance: [
      'Battery and electrical problems can affect the starting system and may cause poor charging or warning lights.',
      'If there is visible damage, overheating, swelling, or burning smell, stop using the vehicle and seek urgent professional help.',
    ],
    safetyLevel: 'caution',
  },
  overheating: {
    category: 'overheating',
    title: 'Overheating',
    keywords: [
      'overheat',
      'boiling',
      'temperature',
      'steam',
      'coolant',
      'hot',
      'radiator',
      ' overheating ',
    ],
    symptoms: [
      'Temperature warning light appears or gauge rises high',
      'Steam, boiling coolant, or strong heat from the engine bay',
      'Vehicle loses power or runs poorly when hot',
    ],
    questions: [
      'Do you see steam, coolant loss, or a high temperature warning?',
      'Is the vehicle still drivable, or does it lose power?',
      'Has the issue happened after heavy driving or low coolant?',
    ],
    guidance: [
      'Severe overheating can cause major engine damage and should be treated seriously.',
      'If the vehicle is steaming, warning lights are flashing, or coolant is leaking, stop driving and arrange professional assistance immediately.',
      'Do not keep driving if the engine is overheating or if there is a significant coolant leak.',
      'Stop somewhere safe and switch off the engine. Do not open the radiator or coolant reservoir cap while the engine is hot.',
    ],
    safetyLevel: 'urgent',
  },
  brakes: {
    category: 'brakes',
    title: 'Brakes',
    keywords: [
      'brakes',
      'brake',
      'pedal',
      'squeal',
      'grinding',
      'brake warning',
      'pulling',
      'stop',
    ],
    symptoms: [
      'Brake warning light is on',
      'Braking feels soft, pulling, vibrating, or noisy',
      'Longer stopping distance or poor response',
    ],
    questions: [
      'Does the brake pedal feel normal, soft, or spongy?',
      'Are there noises or vibration when braking?',
      'Has the vehicle been pulling to one side during braking?',
    ],
    guidance: [
      'Brake-related problems are safety-critical and should be checked promptly by a professional.',
      'If braking performance is significantly reduced, the vehicle may not be safe to drive.',
      'Do not attempt brake component repair without proper training and tools.',
      'A very soft pedal or a car that is not stopping properly should be treated as potentially urgent.',
    ],
    safetyLevel: 'urgent',
  },
  tyres: {
    category: 'tyres',
    title: 'Tyres / Steering / Suspension',
    keywords: [
      'tyre',
      'tire',
      'steering',
      'suspension',
      'wheel',
      'vibration',
      'pulling',
      'alignment',
      'wobble',
    ],
    symptoms: [
      'Vehicle pulls to one side or steering feels loose',
      'Tyre wear is uneven or there are exposed cords',
      'Vibration or wobble while driving',
    ],
    questions: [
      'Has the steering felt loose, heavy, or unstable?',
      'Any vibration in the wheel or steering wheel?',
      'Are there signs of tyre damage, uneven wear, or a puncture?',
      'Does the vibration or pulling happen during braking, acceleration, turning, or at a particular speed?',
    ],
    guidance: [
      'Tyres, steering, and suspension issues can affect control and safety.',
      'If there are visible exposed cords, major tyre damage, or severe steering issues, do not drive the vehicle and seek professional help.',
    ],
    safetyLevel: 'urgent',
  },
  warningLight: {
    category: 'warning-light',
    title: 'Engine Warning Light',
    keywords: [
      'warning light',
      'check engine',
      'engine light',
      'dashboard light',
      'malfunction indicator',
    ],
    symptoms: [
      'Dashboard warning light is on',
      'Engine performance is changed or there are other symptoms',
    ],
    questions: [
      'Which warning light is on, and is the vehicle still driving normally?',
      'Are there any other symptoms such as overheating, rough running, or loss of power?',
      'Is the check-engine light steady or flashing, and is the vehicle shaking or losing power?',
    ],
    guidance: [
      'A warning light may indicate a range of issues, from minor to important mechanical or electrical faults.',
      'A warning light by itself does not confirm a diagnosis; professional inspection is advised when the cause is unclear.',
    ],
    safetyLevel: 'caution',
  },
  transmission: {
    category: 'transmission',
    title: 'Transmission / Gear Shifting',
    keywords: [
      'transmission',
      'gearbox',
      'gear',
      'shifting',
      'slipping',
      'clutch',
      'automatic',
      'manual',
    ],
    symptoms: [
      'Vehicle slips out of gear, jerks, or makes unusual noises',
      'Difficulty changing gear or delayed engagement',
      'Warning light or abnormal drivability while moving',
    ],
    questions: [
      'Does the issue happen when accelerating, changing gear, or idling?',
      'Is the vehicle shuddering, slipping, or delaying engagement?',
      'Does delayed engagement also happen in Reverse or other gears?',
      'Does the delay happen when shifting from Park to Drive?',
    ],
    guidance: [
      'Transmission problems can be serious and often need professional inspection.',
      'If the vehicle is unable to engage gears or there are warning lights, do not continue driving without checking with a professional.',
    ],
    safetyLevel: 'caution',
  },
  ac: {
    category: 'air-conditioning',
    title: 'Air Conditioning',
    keywords: [
      'air conditioning',
      'ac',
      'a c',
      'heater',
      'cooling',
      'temperature',
      'vent',
    ],
    symptoms: [
      'Air conditioning is weak, not cooling, or making unusual noises',
      'Warm air or reduced airflow from vents',
      'Musty smell or signs of refrigerant or water leak',
    ],
    questions: [
      'Is the issue only with cooling, or is the cabin airflow also weak?',
      'Do you notice strange smells or sounds from the vents?',
      'Does the blower work, and does cooling change with engine speed?',
    ],
    guidance: [
      'A/C problems are often not immediate safety hazards unless accompanied by signs such as electrical faults or leaks.',
      'A visible refrigerant leak or major electrical damage should be referred to a professional.',
    ],
    safetyLevel: 'normal',
  },
  noiseSmell: {
    category: 'noise-smell',
    title: 'Unusual Noise / Smell',
    keywords: [
      'noise',
      'sound',
      'smell',
      'burning',
      'grinding',
      'hissing',
      'squeal',
      'chemical',
      'smoke',
      'fuel smell',
      'sweet smell',
    ],
    symptoms: [
      'Burning smell, smoke, or unusual chemical smell',
      'Grinding, squealing, rattling, or hissing noises',
      'Burnt odour from the cabin or engine bay',
    ],
    questions: [
      'What does the smell or noise resemble, and where does it seem to be coming from?',
      'Is the issue constant or only when the vehicle is in use?',
      'Does it sound like squealing, grinding, knocking, rattling, or hissing?',
    ],
    guidance: [
      'Certain smells and noises can be signs of serious mechanical or electrical issues.',
      'If there is smoke, fuel smell, burning electrical smell, or a fire-like symptom, stop driving and seek urgent help.',
    ],
    safetyLevel: 'urgent',
  },
  customerInfo: {
    category: 'customer-info',
    title: 'Customer Information',
    keywords: [
      'name',
      'phone',
      'email',
      'address',
      'vehicle',
      'mileage',
      'service date',
      'location',
    ],
    symptoms: [],
    questions: [
      'May I record your name and contact details?',
      'What is the make, model, and year of the vehicle?',
      'What is the current mileage and when did the problem begin?',
    ],
    guidance: [
      'Collecting a small amount of customer and vehicle information helps the service team understand the issue and arrange follow-up.',
      'Only collect what is necessary to continue the assessment and arrange service.',
    ],
    safetyLevel: 'normal',
  },
  safety: {
    category: 'safety',
    title: 'Safety / Escalation',
    keywords: [
      'fire',
      'smoke',
      'fuel leak',
      'fuel leakage',
      'severe overheating',
      'brake failure',
      'steering failure',
      'electrical damage',
      'exposed tyre',
    ],
    symptoms: [
      'Smoke, fire, fuel leak, major brake or steering issue, or severe overheating',
      'Visible electrical damage or exposed tyre cords',
    ],
    questions: [
      'Are there immediate signs of smoke, fire, leaking fuel, or severe loss of braking or steering?',
    ],
    guidance: [
      'This is a safety-first case. Stop using the vehicle, avoid driving it, and arrange professional assistance immediately.',
      'Do not attempt a repair if the issue is smoke-related, fuel-related, or a major brake/steering fault.',
    ],
    safetyLevel: 'urgent',
  },
};

export const getKnowledgeBaseEntries = () => Object.values(knowledgeBase);
